### PR TITLE
Remove and ignore package-lock.json for now

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by dereke** [comment]
What is the benefit of doing this?
I've always found it extremely useful to have a lock file as it ensures everyone who installs is using the same version of dependencies.
Admittedly I've not used the npm lock only the yarn equivalent

**Comment by ralphtheninja** [comment]
@dereke The benefit right now is that this project is brand new, will most likely change a lot and it causes a lot of noise to update package-lock.json all the time.

**Comment by ralphtheninja** [comment]
That said, once this is considered stable we will most likely bring it back in :smile:

**Comment by dereke** [comment]
Is that a separate process with npm?
With yarn it just manages itself. I've not ever had to intervene.
Cool whatever makes you work faster is good 😂

**Comment by hackergrrl** [comment]
thank you @ralphtheninja :star2:

**Pull request merged**
