### PR TITLE
Add @isomorphic-git's hypergit repo (yay experiments!)

### PR DESCRIPTION
**Pull request by billiegoose**
I'm going to try creating a single repo for the @isomorphic-git project, and namespace the branches by the Github repo name. E.g.
```
> git ls-remote hyper
67f0c3fd63d6c056d858233e188896079083b1b4        refs/heads/isomorphic-git/master
d91f9ac55d3a41f765f6e3e2f13970995c4f2b1e        refs/heads/isomorphic-git.github.io/source
```

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@noffle Oh, this should maybe be in a separate section in the README?

**Comment by hackergrrl** [comment]
oh, ha! I had meant for that section to be "here are the remotes of other people hacking on **hypergit**". I could see how that could be misinterpreted though. I was trying to make it easier to see everyone's forks.

@ralphtheninja maybe you could make a separate section for github projects using hypergit? I wonder if this information would be more useful on the isomorphic-git readme though than here?

**Comment by RangerMauve** [comment]
@wmhilton Does this mean you're going to support Hypergit? :D

**Comment by hackergrrl** [comment]
@wmhilton curious: why did you decide to make each branch a separate remote?

**Comment by ralphtheninja** [comment]
> @ralphtheninja maybe you could make a separate section for github projects using hypergit? I wonder if this information would be more useful on the isomorphic-git readme though than here?

:+1:

**Comment by ralphtheninja** [comment]
https://github.com/noffle/hypergit/commit/11c1c017bf6a13f7f15b09208c9d9c1a9c3c242a

**Comment by billiegoose** [comment]
@RangerMauve I'm not committing to supporting any particular non-standard \*gits at this time... But as one might guess from my pastime, I'm a bit of a git enthusiast. :-) So I'm definitely going to experiment with hypergit.

@noffle I'm experimenting with my [One Repo Hypothesis](https://github.com/noffle/gitverse/issues/1#issuecomment-396016579)

**Comment by billiegoose** [comment]
> I wonder if this information would be more useful on the isomorphic-git readme though than here?

One README at a time... I just got excited is all! Gotta make that background service first...

**Pull request merged**
